POPULATION_SIZE: int = 1000

ELITISM_PERCENTAGE: float = 0.01
SURVIVAL_RATE: float = 0.2
IMMIGRATION_RATE: float = 0.50

MUTATION_RATE: float = 0.9

USE_GENERATION_LIMIT: bool = False
GENERATION_LIMIT: int = 0

USE_FITNESS_CRITERION: bool = True
FITNESS_CRITERION: str = "max"
FITNESS_THRESHOLD: int = 1000
