POPULATION_SIZE: int = 100_000

ELITISM_PERCENTAGE: float = 0.05
SURVIVAL_RATE: float = 0.25

MUTATION_RATE: float = 0.7

USE_GENERATION_LIMIT: bool = True
GENERATION_LIMIT: int = 10

USE_FITNESS_CRITERION: bool = True
FITNESS_CRITERION: str = "max"
FITNESS_THRESHOLD: int = 1000
