POPULATION_SIZE: int = 100_000

ELITISM: int = 1000
SURVIVAL_PERCENTAGE: float = 0.25

MUTATION_RATE: float = 0.7

GENERATION_LIMIT: int = 10
USE_FITNESS_CRITERION: bool = True
FITNESS_CRITERION: str = "max"
FITNESS_THRESHOLD: int = 10000
